import { Request, Response } from "express";

export const getAiSuggestions = (req: Request, res: Response) => {
    res.json({ 
      result: { 
        suggestions: [
          { title: "Sample derived task", description: "Generated by local backend", priority: "medium" }
        ], 
        subtasks: [], 
        recommendations: [], 
        summary: "AI analysis complete." 
      } 
    });
};
